sudo: false
language: node_js
node_js:
  - "4.1"
  - "4.0"
services:
  - mongodb
install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g mocha
  - npm install
before_script:
  - bower install
  - grunt