sudo: false
language: node_js
node_js:
  - "4.1"
  - "4.0"
services:
  - mongodb
install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g mocha
  - npm install -g codecov
  - npm install
before_script:
  - bower install
  - grunt
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov